### PR TITLE
Omit strength text

### PR DESCRIPTION
**Pull request by Diet-Cola**

### CODE REVIEW

**Comment by ProgrammerDan** [comment]
I don't really understand the impetus for this change, but it's a clean change lol

**Comment by Diet-Cola** [comment]
When trying to hand mine a bastion before this change, it would throw an NPE getting the strength of the bastion to put in the hover message of the 'Bastion deleted' text, this just simply omits the strength text to allow bastions to drop when broken by hand again

**Comment by ProgrammerDan** [comment]
Ahahahha, wow. Ok, ty.

Should it preferentially be gated behind a null check? Is there any other
use where it is helpful?

**Comment by Diet-Cola** [comment]
I think I removed it here since its displayed when creating a bastion/removing a bastion/clicking a bastion for info, all of which has the strength of the bastion already available there by reinforcement

**Pull request merged**
