### PR TITLE
Update version and stop boat placements

### PR DESCRIPTION
**Pull request by MrLittleKitty**
Stop boat placements in Bastioned areas and increment version number

### CODE REVIEW

**Comment by DevotedServant** [comment]
Can one of the admins verify this patch? @ProgrammerDan @Maxopoly

"ok to test" will build any commits made to this PR
"test this please" will build this PR once
"retest this please" will make another single build for this PR
"add to whitelist" will whitelist the creator of this PR and make jenkins automatically build any PRs made by him

**Comment by ProgrammerDan** [comment]
Yeah, in the future just commit to the same branch, it'll just update the PR :)

Thank you!

**Comment by ProgrammerDan** [comment]
ok to test

**Comment by MrLittleKitty** [comment]
Ok but maybe I want to pad my Github PR's for future employers to see on my profile... ;)

**Pull request merged**
