### PR TITLE
Attempt to stop boat places in bastioned areas

### PR DESCRIPTION
**Pull request by MrLittleKitty**
Tested this for this branch (1.10-fix) on Minecraft 1.10.2 and it works.

### CODE REVIEW

**Comment by DevotedServant** [comment]
Can one of the admins verify this patch? @ProgrammerDan @Maxopoly

"ok to test" will build any commits made to this PR
"test this please" will build this PR once
"retest this please" will make another single build for this PR
"add to whitelist" will whitelist the creator of this PR and make jenkins automatically build any PRs made by him

**Comment by ProgrammerDan** [comment]
ok to test

**Review by ProgrammerDan — COMMENTED** [review]
Please update pom.xml version by one increment, thanks!

**Comment by ProgrammerDan** [comment]
Closed? You can just commit a new change to the same branch and it'll update this PR?

**Comment by MrLittleKitty** [comment]
Idk? Seemed safer to just close and open a new one.

**Pull request closed without merging**
